---
- name: Installing Nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Checking the existence of the nginx group
  become: yes
  command: getent group nginx
  register: nginx_group_exists
  changed_when: false
  ignore_errors: yes

- name: Create nginx group (if it doesn't exist)
  become: yes
  group:
    name: nginx
    state: present
  when: nginx_group_exists.rc != 0

- name: Creating an SSL directory
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0750
    owner: root
    group: "{{ 'nginx' if nginx_group_exists.rc == 0 else 'root' }}"

- name: Generating a private key
  become: yes
  openssl_privatekey:
    path: "{{ nginx_ssl_key_path }}"
    size: 2048
    mode: 0640
    owner: root
    group: "{{ 'nginx' if nginx_group_exists.rc == 0 else 'root' }}"

- name: Generate a self-signed certificate
  become: yes
  openssl_certificate:
    path: "{{ nginx_ssl_cert_path }}"
    privatekey_path: "{{ nginx_ssl_key_path }}"
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    selfsigned_digest: "sha256"
    selfsigned_version: 3
    mode: 0644
    owner: root
    group: "{{ 'nginx' if nginx_group_exists.rc == 0 else 'root' }}"

- name: Setting up Nginx
  become: yes
  template:
    src: nginx-https.conf.j2
    dest: /etc/nginx/conf.d/superset.conf
    mode: 0644
    owner: root
    group: root
  notify: restart nginx

- name: Checking Nginx Configuration
  become: yes
  command: nginx -t
  register: nginx_test
  changed_when: false
  notify: reload nginx

- name: Enabling and starting Nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

- name: Install node_exporter for system metrics
  become: yes
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes
  notify: restart prometheus-node-exporter

- name: Install Docker and dependencies
  become: yes
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure promtail directories exist
  become: yes
  file:
    path: "/opt/promtail/config"
    state: directory
    mode: '0755'

- name: Deploy promtail config
  become: yes
  template:
    src: promtail-config.yml.j2
    dest: "/opt/promtail/config/config.yml"
    mode: '0644'

- name: Deploy docker-compose for promtail
  become: yes
  copy:
    src: docker-compose-promtail.yml
    dest: "/opt/promtail/docker-compose.yml"
    mode: '0644'

- name: Run promtail with Docker Compose
  become: yes
  command: docker-compose up -d
  args:
    chdir: /opt/promtail

- name: Install UFW
  become: yes
  apt:
    name: ufw
    state: present

- name: Reset UFW (optional)
  become: yes
  ufw:
    state: reset
  when: reset_ufw | default(false)

# Определяем интерфейсы
- name: Get public interface name
  become: yes
  shell: |
    ip -o -4 addr show | grep 192.168.0.100 | awk '{print $2}'
  register: public_interface
  changed_when: false

# Устанавливаем политики по умолчанию
- name: Allow all incoming by default
  become: yes
  ufw:
    default: allow
    direction: incoming

- name: Allow all outgoing by default
  become: yes
  ufw:
    default: allow
    direction: outgoing

# Блокируем SSH на внешнем интерфейсе
- name: Block SSH on public interface
  become: yes
  command: "ufw deny in on {{ public_interface.stdout }} proto tcp to any port 22"

# Включаем UFW
- name: Enable UFW
  become: yes
  ufw:
    state: enabled

# Проверка
- name: Verify UFW status
  become: yes
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Display UFW rules
  debug:
    var: ufw_status.stdout
