---
- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    enabled: true

- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    enabled: true

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
    enabled: true