---
# handlers/main.yml
- name: restart postgresql
  become: yes
  service:
    name: postgresql
    state: restarted

- name: restart prometheus-node-exporter
  become: yes
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted