apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  isDefault: true
  jsonData:
    timeInterval: "15s"
    httpMethod: "POST"

- name: Loki
  type: loki
  url: http://loki:3100
  access: proxy
  jsonData:
    maxLines: 1000
    derivedFields:
      - datasourceUid: 'prometheus'
        matcherRegex: 'traceID=(\w+)'
        name: 'TraceID'
        url: '$${__value.raw}'
