---
- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    enabled: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true

- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    enabled: true