global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fw-proxy'
    static_configs:
      - targets: ['10.0.0.10:9100']

  - job_name: 'superset1'
    static_configs:
      - targets: ['10.0.0.11:9100']

  - job_name: 'superset2'
    static_configs:
      - targets: ['10.0.0.12:9100']

  - job_name: 'pg1'
    static_configs:
      - targets: ['10.0.0.21:9100']

  - job_name: 'pg2'
    static_configs:
      - targets: ['10.0.0.22:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093