apiVersion: 1
groups:
    - orgId: 1
      name: Otus
      folder: Host Availability
      interval: 1m
      rules:
        - uid: eeuhcdp4ewhs0e
          title: Otus Linux.Professional
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: builder
                expr: up
                instant: true
                interval: ""
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: eq
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Хост {{ $labels.instance }} недоступен!
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Telegram
