net_config: |
      source-directory /etc/network/interfaces.d

      auto lo
      iface lo inet loopback

      # auto eth0
      # allow-hotplug eth0
      # iface eth0 inet dhcp

      auto eth0
      allow-hotplug eth0
      iface eth0 inet static
            address 10.0.2.15
            netmask 255.255.255.0

      auto eth1
      iface eth1 inet static
            address 192.168.255.6
            netmask 255.255.255.252
            gateway 192.168.255.5
            post-up ip route add default via 192.168.255.5 dev eth1

            auto eth2
            iface eth2 inet static
                  address 192.168.1.1
                  netmask 255.255.255.128

            auto eth3
            iface eth3 inet static
                  address 192.168.1.129
                  netmask 255.255.255.192

            auto eth4
            iface eth4 inet static
                  address 192.168.1.193
                  netmask 255.255.255.192

            auto eth5
            iface eth5 inet static
                  address 192.168.60.30
                  netmask 255.255.255.0


ansible_private_key_file: .vagrant/machines/office2Router/virtualbox/private_key

